# Generated by Django 5.1.1 on 2024-10-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_blog_contact_alter_product_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="heading",
            field=models.TextField(max_length=100, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="sing_of_publication",
            field=models.BooleanField(default=True, verbose_name="признак публикации"),
        ),
    ]
