# Generated by Django 5.1.1 on 2024-10-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_blog_heading_alter_blog_sing_of_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="count_views",
            field=models.IntegerField(default=0, verbose_name="количество просмотров"),
        ),
    ]
