# Generated by Django 5.1.1 on 2024-10-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_blog_count_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="count_views",
            field=models.PositiveIntegerField(
                default=0, verbose_name="количество просмотров"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="содержимое"
            ),
        ),
    ]
