# Generated by Django 4.2.2 on 2024-10-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "price"],
                "permissions": [
                    (
                        "can_cancel_publication",
                        "can cancel the publication of a product",
                    ),
                    (
                        "can_change_description",
                        "can change the description of any product",
                    ),
                    ("can_change_category", "can change the category of any product"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="sing_of_publication",
            field=models.BooleanField(default=False, verbose_name="признак публикации"),
        ),
    ]
